[package]
name = "auto-merge-dependabot-pull-requests-webhook"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros"] }

[dependencies.lambda_http]
version = "0.13.0"
features = ["pass_through"]
