permissions:
  contents: none # Minimal default permissions

on:
  workflow_call: # From .github/workflows/release.yml
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  all-jobs:
    name: all-jobs
    if: always() # Otherwise this job is skipped if the matrix job fails
    runs-on: ubuntu-latest
    needs:
      - lint-and-build
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'

  lint-and-build:
    name: lint-and-build
    runs-on: ubuntu-latest
    permissions:
      contents: read # For actions/checkout@v4
    steps:
      - uses: actions/checkout@v4
      - run: ( cd rust-webhook && cargo fmt --check && cargo clippy && cargo build )
